### ISSUE TITLE
Add original data documentation

### ISSUE THREAD

**Issue by dmi3kno** [topepo/AmesHousing#1]
Hi and thanks for awesome package. Since you include ames_raw , i think it makes all sense to ship original Data Documentation file either as vignette or as raw txt file for users to understand original name conventions and the context for certain variables. 
https://ww2.amstat.org/publications/jse/v19n3/Decock/DataDocumentation.txt

I found some of the special notes towards the end of the file extremely useful, in particular regarding outliers. They mess up the models quite badly, as we discovered on [Kaggle](https://www.kaggle.com/c/house-prices-advanced-regression-techniques)

**Comment by topepo** [comment]
See the update. I added the variable names and descriptions but avoided all of the text on the levels. If you want to add them, a PR would work. Keep in mind though that the values might be different in the processed version(s). 

I'll target sending this to CRAN at the end of the week, so let me know if you see anything wrong with the updates for these two issues before then.

**Comment by dmi3kno** [comment]
Thank you
